const words = {
  Easy: [
    'apple',
    'banana',
    'cat',
    'dog',
    'elephant',
    'fish',
    'house',
    'tree',
    'water',
    'world',
    'happy',
    'milk',
    'sun',
    'car',
    'bird', // Added more easy words
    'color',
    'food',
    'friend',
  ],
  Moderate: [
    'beautiful',
    'comfortable',
    'difficult',
    'enormous',
    'fantastic',
    'government',
    'important',
    'intelligent',
    'interesting',
    'language',
    'adventure',
    'celebrate',
    'different',
    'friendship',
    'knowledge', // Added more moderate words
    'music',
    'nature',
    'science',
  ],
  Hard: [
    'bureaucracy',
    'conscientious',
    'extracurricular',
    'heterogeneous',
    'infinitesimal',
    'juxtaposition',
    'labyrinth',
    'meticulous',
    'photosynthesis',
    'surreptitious',
    'archaeology',
    'equilibrium',
    'philosophy',
    'typography',
    'ambiguity', // Added more hard words
    'constellation',
    'hypothesis',
    'metaphor',
  ],
}

export default words
